complete -c mc -s f -l force -d 'Overwrite destination if it exists'
complete -c mc -l hard-link -d 'Hard link file'
complete -c mc -l symlink -d 'Symbol link file'
complete -c mc -l reflink -d 'Ref link file Similar to hardlink except modify one doesn\'t affect the other'
complete -c mc -l verify -d 'Verify hash of folder / file once copied'
complete -c mc -l no-progress -d 'Disable progress bar'
complete -c mc -l no-keep-awake -d 'Disable keep system awake while copy'
complete -c mc -l keep-display-awake -d 'Keep display awake while copy'
complete -c mc -s h -l help -d 'Print help'
